### ISSUE TITLE
libOpenNI2.dylib

### ISSUE THREAD

**Issue by Kish27051995** [KirillLykov/oni2avi#11]
After doing make in the build directory, i get the following error. How do i  resolve this?
I'm using Ubuntu 14.04
Scanning dependencies of target oni2avi
[100%] Building CXX object CMakeFiles/oni2avi.dir/oni2avi.cpp.o
make[2]: *** No rule to make target `/usr/local/lib/ni2/libOpenNI2.dylib', needed by `oni2avi'.  Stop.
make[1]: *** [CMakeFiles/oni2avi.dir/all] Error 2
make: *** [all] Error 2

**Comment by KirillLykov** [comment]
The problem is that make cannot find `/usr/local/lib/ni2/libOpenNI2.dylib`. So check if OpenNI2 has been installed, if yes - in which directory. If the path `/usr/local/lib/ni2/` is correct, show me what this folder contains. 
If your ubuntu doesn't have openni2, it should have v1.5, try to check out  legacy version of oni2avi (see Readme).
